testing support for custom names
harshhhdev/birthday-celebration pull request #1
Opened 2020-11-17 17:57 UTC by minidevz

This might not work since i need to test it in the actual github.io link, but ill fix it if it doesn't :p

2020-11-18 23:16 UTC, harshhhdev requested changes
Bring the output to the bottom, so it does not show a null reference.

2020-11-18 23:16 UTC, harshhhdev commented on index.html
> +      </script>
Here, you need to bring this script to the bottom so it does not show a null reference.

2020-11-18 23:18 UTC, harshhhdev reviewed
Add a name to the JS code instead of having 2 seperate elements.

2020-11-18 23:18 UTC, harshhhdev commented on index.html
> +      <h1 class="title">Happy Birthday</h1> <h1 id="output"></h1>
Instead of this, in the name you can do `Happy Birthday ${name}`

2020-11-19 11:04 UTC, minidevz commented on index.html
> +      <h1 class="title">Happy Birthday</h1> <h1 id="output"></h1>
That doesn't work in HTML though.

2020-11-19 11:13 UTC, minidevz commented
Made all changes other than the ${name} one (since thats not possible in HTML), should be good to go.

2020-11-19 17:06 UTC, harshhhdev reviewed
> Made all changes other than the ${name} one (since thats not possible in HTML), should be good to go.

Sorry. I should’ve made it more clear what I wanted. I wanted the string interpolation in JS, not the HTML (since it’s not possible to do). No need for 2 h1 tags.

Other than that it’s good 👍🏽Just have only one h1 element and do the string interp in the JS and I’ll merge when I get home from school

2020-11-19 17:06 UTC, harshhhdev commented on index.html
> +      document.getElementById('output').innerHTML = name + "!";
Only one h1 element instead of 2. For output you can do ‘Happy Birthday ${name}’

2020-11-20 09:01 UTC, minidevz commented on index.html
> +      document.getElementById('output').innerHTML = name + "!";
yeah i get it thanks.

2020-11-20 15:34 UTC, minidevz commented
I think ive made all the changes you needed, also vertically centered the happy birthday text because it looks better that way, think we should be good to go

2020-11-20 15:35 UTC, harshhhdev approved these changes

2020-11-20 15:36 UTC, merged

2020-11-20 15:36 UTC, harshhhdev commented
Yep, thanks for this.